#catalog_index:
#  path: /catalog
#  controller: App\CatalogBundle\Controller\CatalogController::index
#
#catalog_new:
#  path: /catalog/new
#  controller: App\CatalogBundle\Controller\CatalogController::newItem

#catalog.list:
#  path: /catalog
#  controller: App\CatalogBundle\Controller\CatalogController::index