version: '3.7'

services:
    php:
        container_name: php-fpm
        build: ./php
        ports:
            - "9000:9001"
        volumes:
            - ./app:/var/www/app
            - ./logs/php:/var/log/php7
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./app:/var/www/app:cached
            - ./logs/nginx:/var/log/nginx:cached
#    composer:
#        container_name: composer
#        restart: 'no'
#        image: composer/composer:php7
#        command: install
#        volumes:
#            - ./app:/app
#    postgres:
#        container_name: psql
#        image: postgres:9.6-alpine
#        volumes:
#            - ./db/psql:/var/lib/postgresql/data
#        ports:
#            - "5432:5432"
#        environment:
#            - DB_NAME=local
#            - DB_USER=local
#            - DB_PASS=pass