<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUvAgPY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUvAgPY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMUvAgPY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMUvAgPY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMUvAgPY\App_KernelDevDebugContainer([
    'container.build_hash' => 'MUvAgPY',
    'container.build_id' => '2c26d142',
    'container.build_time' => 1578652825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUvAgPY');
